[package]
name = "firewall_audit"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
ipnet = "2"
regex = "1"
serde_yaml = "0.9"
windows_firewall = "0.1.5"
optional-field = "0.1.6"
tempfile = "3"

[target.'cfg(windows)'.dependencies]
windows_firewall = "0.1"

[features]
debug = []

[lib]
name = "firewall_audit"
path = "src/lib.rs"
