[package]
name = "firewall_audit"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ipnet = "2.7"
optional-field = "0.1.6"
serde_yaml = "0.9.34"

[target.'cfg(windows)'.dependencies]
windows_firewall = "0.1"
